.RP no

.TL
Computer Project
.AU
Aanjishnu Bhattacharyya

.SH
Hello, World 

.PP
This is a small test type setting lol
This thing should look atleast descent IDK if it will or not but
I mean it should I designed it to honestly

.TS
allbox tab(&);
cb cb cb cb
l l l l.
Name & Function & Type & Scope
A    &
T{
Your mom love this,
even better than
your dad
T}& int & main
A    & Your mom love this, even better than your dad & int & main
A    & Your mom love this, even better than your dad & int & main
A    & Your mom love this, even better than your dad & int & main
A    & Your mom love this, even better than your dad & int & main
A    & Your mom love this, even better than your dad & int & main
A    & Your mom love this, even better than your dad & int & main
.TE
